/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
var styles = ["label[_ngcontent-%COMP%]{\n    padding: 20px;\n}\n\n.avatar[_ngcontent-%COMP%] {\n     height:80px;\n     width: 80px;\n     border-radius: 100% ;\n     -webkit-border-radius: 100% ;\n     -moz-border-radius: 100% ;\n     -ms-border-radius: 100% ;\n     -o-border-radius: 100% ;\n}"];
export { styles as styles };
//# sourceMappingURL=mosh-github-followers.component.css.shim.ngstyle.js.map